name: BlockyChat
main: com.blockycraft.blockychat.BlockyChat
version: 1.1.0
author: Bernardo Zukerman
description: Chat customizado integrado ao BlockyGroups e com funcionalidade de greentext.
depend: [BlockyGroups]